### ISSUE TITLE
Sort files by application definition

### ISSUE THREAD

**Issue by benajamin** [nexusformat/exampledata#20]
It is difficult to find an example of a specific application definition, which is what most people coming to this repository will want to do.

**Comment by benajamin** [comment]
Possible solutions include:
- reorder files in directories based on the application definition
- rename files to make the application definition more easily discoverable
- modify critique.py to create a listing of the files according to the application definition (as well as container file type and facility)

**Comment by benajamin** [comment]
Perhaps the wiki attached to the exampledata repo could be used somehow?

**Comment by benajamin** [comment]
Ideally, people should be able to browse file lists that are ordered (or one list that can be reordered) in terms of:
- application definition
- container file type (eg HDF4, HDF5, XML)
- creator facility/program

It is unlikely that Github will allow multiple ordering types on the files, so modifying critique.py to produce more useful output is probably the best way forward.

**Comment by prjemian** [comment]
The wiki is a good way to provide different groupings of the examples.

**Comment by benajamin** [comment]
Yes, but can we automatically update it?

**Comment by benajamin** [comment]
Is the file ANSTO/hdf4/PLP0006018.nx.hdf really in HDF4? It seems to open fine with HDFCompass and has a "HDF5_Version" attribute in the root.
